### ISSUE TITLE
HXi Shift not supported?

### ISSUE THREAD

**Issue by AlexP11223** [Benzhaomin/corsairpsu#10]
I have a HX1500i PSU and I don't see it in `sensors` (Linux kernel 6.17). In `lsusb` there is only `Bus 003 Device 007: ID 1b1c:0c3f Corsair iCUE LINK System Hub` (the hub is integrated into the PSU).

**Comment by Benzhaomin** [comment]
Thanks for the report, fixed in 0e32bd1 in this module but if you use a regular kernel you should have support out of the box, no need for this module.

**Comment by AlexP11223** [comment]
For me it is still the same, standard 6.19 on Arch Linux. 
Maybe the fix was not for the Shift models (which launched in the second half of 2025)?

**Comment by Benzhaomin** [comment]
Hi, you're probably right. All we need to add support might be its product ID.

One way is to check kernel messages for Corsair devices (vendor `1b1c`) with `sudo dmesg | grep 1b1c`:
```
[    1.479021] usb 1-12: New USB device found, idVendor=1b1c, idProduct=1c0a, bcdDevice= 0.0`
```
Another option is to check USB devices with `sudo lsusb -v | grep -A 2 Corsair`:

```
Bus 001 Device 002: ID 1b1c:1c0a Corsair
Negotiated speed: Full Speed (12Mbps)
Device Descriptor:
--
  idVendor           0x1b1c Corsair
  idProduct          0x1c0a
  bcdDevice            0.02
```

Here we find `idProduct==0x1c0a` in both cases, which corresponds to `	{ HID_USB_DEVICE(USB_VENDOR_ID_CORSAIR, 0x1c0a) }, // RM650i` in https://github.com/Benzhaomin/corsairpsu/blob/master/corsairpsu.c#L825 so my RM650i is supported ✅ 

```
$ sensors
corsairpsu-hid-3-1
Adapter: HID adapter
v_in:        230.00 V
v_out +12v:   12.09 V  (crit min =  +8.41 V, crit max = +15.59 V)
v_out +5v:     5.01 V  (crit min =  +3.50 V, crit max =  +6.50 V)
v_out +3.3v:   3.28 V  (crit min =  +2.31 V, crit max =  +4.30 V)
psu fan:        0 RPM
vrm temp:     +47.8°C  (crit = +70.0°C)
case temp:    +41.8°C  (crit = +70.0°C)
power total:  80.00 W
power +12v:   62.00 W
power +5v:    14.00 W
power +3.3v:   5.00 W
curr +12v:     5.25 A  (crit max = +65.00 A)
curr +5v:      2.81 A  (crit max = +40.00 A)
curr +3.3v:    1.69 A  (crit max = +40.00 A)
pwm1:             34%
```

In your case it should be `0c3f` based on what you provided before but let's make sure it is. 

You could also patch and rebuild the driver to see how it goes:

```
diff --git a/corsairpsu.c b/corsairpsu.c
index 0ac712f..76362bf 100644
--- a/corsairpsu.c
+++ b/corsairpsu.c
@@ -836,6 +836,7 @@ static const struct hid_device_id corsairpsu_devices[] = {
        { HID_USB_DEVICE(USB_VENDOR_ID_CORSAIR, 0x1c23) }, // HX1200i Series 2023
        { HID_USB_DEVICE(USB_VENDOR_ID_CORSAIR, 0x1c27) }, // HX1200i Series 2025
        { HID_USB_DEVICE(USB_VENDOR_ID_CORSAIR, 0x1c1f) }, // HX1500i legacy and Series 2023
+       { HID_USB_DEVICE(USB_VENDOR_ID_CORSAIR, 0x0c3f) }, // HX1500i Series 2025
        {}
 };
```

**Comment by AlexP11223** [comment]
Yeah, for me it is

```
$ sudo dmesg | grep 1b1c
[    5.552221] usb 3-8: New USB device found, idVendor=1b1c, idProduct=0c3f, bcdDevice= 1.00
```

```
$ sudo lsusb -v | grep -A 2 Corsair
Bus 003 Device 007: ID 1b1c:0c3f Corsair iCUE LINK System Hub
Negotiated speed: High Speed (480Mbps)
Device Descriptor:
--
  idVendor           0x1b1c Corsair
  idProduct          0x0c3f iCUE LINK System Hub
  bcdDevice            1.00
  iManufacturer           1 Corsair
  iProduct                2 iCUE LINK System Hub
```
